// Catálogo oficial de división territorial de Costa Rica: 7 provincias,
// 84 cantones y sus distritos. Fuente: Wikipedia "Anexo:Cantones de Costa
// Rica" y "Anexo:Distritos de Costa Rica" (basados en el Decreto Ejecutivo
// N.° 44882-MGP, Declaratoria Oficial de la División Territorial
// Administrativa, La Gaceta N.° 17, 28/01/2025), con los cantones más
// nuevos (Monteverde y Puerto Jiménez, cada uno de distrito único) y los
// distritos Pijije (Bagaces) y Cabagra (Buenos Aires), creados en mayo 2025.
//
// Se usa para los selects en cascada Provincia -> Cantón -> Distrito del
// formulario de Solicitud de Paja de Agua (y cualquier otro formulario que
// necesite ubicación exacta sin margen de error de digitación).

export const PROVINCIAS: string[] = [
  'San José',
  'Alajuela',
  'Cartago',
  'Heredia',
  'Guanacaste',
  'Puntarenas',
  'Limón',
];

// Cantones agrupados por provincia, en el orden oficial (por año de creación).
export const CANTONES_POR_PROVINCIA: Record<string, string[]> = {
  'San José': [
    'San José',
    'Escazú',
    'Desamparados',
    'Puriscal',
    'Tarrazú',
    'Aserrí',
    'Mora',
    'Goicoechea',
    'Santa Ana',
    'Alajuelita',
    'Vázquez de Coronado',
    'Acosta',
    'Tibás',
    'Moravia',
    'Montes de Oca',
    'Turrubares',
    'Dota',
    'Curridabat',
    'Pérez Zeledón',
    'León Cortés Castro',
  ],
  'Alajuela': [
    'Alajuela',
    'San Ramón',
    'Grecia',
    'San Mateo',
    'Atenas',
    'Naranjo',
    'Palmares',
    'Poás',
    'Orotina',
    'San Carlos',
    'Zarcero',
    'Sarchí',
    'Upala',
    'Los Chiles',
    'Guatuso',
    'Río Cuarto',
  ],
  'Cartago': [
    'Cartago',
    'Paraíso',
    'La Unión',
    'Jiménez',
    'Turrialba',
    'Alvarado',
    'Oreamuno',
    'El Guarco',
  ],
  'Heredia': [
    'Heredia',
    'Barva',
    'Santo Domingo',
    'Santa Bárbara',
    'San Rafael',
    'San Isidro',
    'Belén',
    'Flores',
    'San Pablo',
    'Sarapiquí',
  ],
  'Guanacaste': [
    'Liberia',
    'Nicoya',
    'Santa Cruz',
    'Bagaces',
    'Carrillo',
    'Cañas',
    'Abangares',
    'Tilarán',
    'Nandayure',
    'La Cruz',
    'Hojancha',
  ],
  'Puntarenas': [
    'Puntarenas',
    'Esparza',
    'Buenos Aires',
    'Montes de Oro',
    'Osa',
    'Quepos',
    'Golfito',
    'Coto Brus',
    'Parrita',
    'Corredores',
    'Garabito',
    'Monteverde',
    'Puerto Jiménez',
  ],
  'Limón': [
    'Limón',
    'Pococí',
    'Siquirres',
    'Talamanca',
    'Matina',
    'Guácimo',
  ],
};

// Distritos agrupados por cantón. OJO: algunos nombres de cantón se repiten
// entre provincias (ej. 'Liberia' es cantón de Guanacaste y cabecera de otros),
// pero los NOMBRES DE CANTÓN en Costa Rica son únicos a nivel nacional, así que
// esta tabla se indexa solo por cantón (no hace falta anidar por provincia).
export const DISTRITOS_POR_CANTON: Record<string, string[]> = {
  'San José': [
    'Carmen',
    'Merced',
    'Hospital',
    'Catedral',
    'Zapote',
    'San Francisco de Dos Ríos',
    'Uruca',
    'Mata Redonda',
    'Pavas',
    'Hatillo',
    'San Sebastián',
  ],
  'Escazú': [
    'Escazú',
    'San Antonio',
    'San Rafael',
  ],
  'Desamparados': [
    'Desamparados',
    'San Miguel',
    'San Juan de Dios',
    'San Rafael Arriba',
    'San Antonio',
    'Frailes',
    'Patarrá',
    'San Cristóbal',
    'Rosario',
    'Damas',
    'San Rafael Abajo',
    'Gravilias',
    'Los Guido',
  ],
  'Puriscal': [
    'Santiago',
    'Mercedes Sur',
    'Barbacoas',
    'Grifo Alto',
    'San Rafael',
    'Candelarita',
    'Desamparaditos',
    'San Antonio',
    'Chires',
  ],
  'Tarrazú': [
    'San Marcos',
    'San Lorenzo',
    'San Carlos',
  ],
  'Aserrí': [
    'Aserrí',
    'Tarbaca',
    'Vuelta de Jorco',
    'San Gabriel',
    'Legua',
    'Monterrey',
    'Salitrillos',
  ],
  'Mora': [
    'Colón',
    'Guayabo',
    'Tabarcia',
    'Piedras Negras',
    'Picagres',
    'Jaris',
    'Quitirrisí',
  ],
  'Goicoechea': [
    'Guadalupe',
    'San Francisco',
    'Calle Blancos',
    'Mata de Plátano',
    'Ipís',
    'Rancho Redondo',
    'Purral',
  ],
  'Santa Ana': [
    'Santa Ana',
    'Salitral',
    'Pozos',
    'Uruca',
    'Piedades',
    'Brasil',
  ],
  'Alajuelita': [
    'Alajuelita',
    'San Josecito',
    'San Antonio',
    'Concepción',
    'San Felipe',
  ],
  'Vázquez de Coronado': [
    'San Isidro',
    'San Rafael',
    'Dulce Nombre de Jesús',
    'Patalillo',
    'Cascajal',
  ],
  'Acosta': [
    'San Ignacio',
    'Guaitil',
    'Palmichal',
    'Cangrejal',
    'Sabanillas',
  ],
  'Tibás': [
    'San Juan',
    'Cinco Esquinas',
    'Anselmo Llorente',
    'León XIII',
    'Colima',
  ],
  'Moravia': [
    'San Vicente',
    'San Jerónimo',
    'La Trinidad',
  ],
  'Montes de Oca': [
    'San Pedro',
    'Sabanilla',
    'Mercedes',
    'San Rafael',
  ],
  'Turrubares': [
    'San Pablo',
    'San Pedro',
    'San Juan de Mata',
    'San Luis',
    'Carara',
  ],
  'Dota': [
    'Santa María',
    'Jardín',
    'Copey',
  ],
  'Curridabat': [
    'Curridabat',
    'Granadilla',
    'Sánchez',
    'Tirrases',
  ],
  'Pérez Zeledón': [
    'San Isidro de El General',
    'El General',
    'Daniel Flores',
    'Rivas',
    'San Pedro',
    'Platanares',
    'Pejibaye',
    'Cajón',
    'Barú',
    'Río Nuevo',
    'Páramo',
    'La Amistad',
  ],
  'León Cortés Castro': [
    'San Pablo',
    'San Andrés',
    'Llano Bonito',
    'San Isidro',
    'Santa Cruz',
    'San Antonio',
  ],
  'Alajuela': [
    'Alajuela',
    'San José',
    'Carrizal',
    'San Antonio',
    'Guácima',
    'San Isidro',
    'Sabanilla',
    'San Rafael',
    'Río Segundo',
    'Desamparados',
    'Turrúcares',
    'Tambor',
    'Garita',
    'Sarapiquí',
  ],
  'San Ramón': [
    'San Ramón',
    'Santiago',
    'San Juan',
    'Piedades Norte',
    'Piedades Sur',
    'San Rafael',
    'San Isidro',
    'Ángeles',
    'Alfaro',
    'Volio',
    'Concepción',
    'Zapotal',
    'Peñas Blancas',
    'San Lorenzo',
  ],
  'Grecia': [
    'Grecia',
    'San Isidro',
    'San José',
    'San Roque',
    'Tacares',
    'Puente de Piedra',
    'Bolívar',
  ],
  'San Mateo': [
    'San Mateo',
    'Desmonte',
    'Jesús María',
    'Labrador',
  ],
  'Atenas': [
    'Atenas',
    'Jesús',
    'Mercedes',
    'San Isidro',
    'Concepción',
    'San José',
    'Santa Eulalia',
    'Escobal',
  ],
  'Naranjo': [
    'Naranjo',
    'San Miguel',
    'San José',
    'Cirrí Sur',
    'San Jerónimo',
    'San Juan',
    'El Rosario',
    'Palmitos',
  ],
  'Palmares': [
    'Palmares',
    'Zaragoza',
    'Buenos Aires',
    'Santiago',
    'Candelaria',
    'Esquipulas',
    'La Granja',
  ],
  'Poás': [
    'San Pedro',
    'San Juan',
    'San Rafael',
    'Carrillos',
    'Sabana Redonda',
  ],
  'Orotina': [
    'Orotina',
    'El Mastate',
    'Hacienda Vieja',
    'Coyolar',
    'La Ceiba',
  ],
  'San Carlos': [
    'Quesada',
    'Florencia',
    'Buenavista',
    'Aguas Zarcas',
    'Venecia',
    'Pital',
    'La Fortuna',
    'La Tigra',
    'La Palmera',
    'Venado',
    'Cutris',
    'Monterrey',
    'Pocosol',
  ],
  'Zarcero': [
    'Zarcero',
    'Laguna',
    'Tapesco',
    'Guadalupe',
    'Palmira',
    'Zapote',
    'Brisas',
  ],
  'Sarchí': [
    'Sarchí Norte',
    'Sarchí Sur',
    'Toro Amarillo',
    'San Pedro',
    'Rodríguez',
  ],
  'Upala': [
    'Upala',
    'Aguas Claras',
    'San José',
    'Bijagua',
    'Delicias',
    'Dos Ríos',
    'Yolillal',
    'Canalete',
  ],
  'Los Chiles': [
    'Los Chiles',
    'Caño Negro',
    'El Amparo',
    'San Jorge',
  ],
  'Guatuso': [
    'San Rafael',
    'Buenavista',
    'Cote',
    'Katira',
  ],
  'Río Cuarto': [
    'Río Cuarto',
    'Santa Rita',
    'Santa Isabel',
  ],
  'Cartago': [
    'Oriental',
    'Occidental',
    'Carmen',
    'San Nicolás',
    'Aguacaliente',
    'Guadalupe',
    'Corralillo',
    'Tierra Blanca',
    'Dulce Nombre',
    'Llano Grande',
    'Quebradilla',
  ],
  'Paraíso': [
    'Paraíso',
    'Santiago',
    'Orosi',
    'Cachí',
    'Llanos de Santa Lucía',
    'Birrisito',
  ],
  'La Unión': [
    'Tres Ríos',
    'San Diego',
    'San Juan',
    'San Rafael',
    'Concepción',
    'Dulce Nombre',
    'San Ramón',
    'Río Azul',
  ],
  'Jiménez': [
    'Juan Viñas',
    'Tucurrique',
    'Pejibaye',
    'La Victoria',
  ],
  'Turrialba': [
    'Turrialba',
    'La Suiza',
    'Peralta',
    'Santa Cruz',
    'Santa Teresita',
    'Pavones',
    'Tuis',
    'Tayutic',
    'Santa Rosa',
    'Tres Equis',
    'La Isabel',
    'Chirripó',
  ],
  'Alvarado': [
    'Pacayas',
    'Cervantes',
    'Capellades',
  ],
  'Oreamuno': [
    'San Rafael',
    'Cot',
    'Potrero Cerrado',
    'Cipreses',
    'Santa Rosa',
  ],
  'El Guarco': [
    'El Tejar',
    'San Isidro',
    'Tobosi',
    'Patio de Agua',
  ],
  'Heredia': [
    'Heredia',
    'Mercedes',
    'San Francisco',
    'Ulloa',
    'Varablanca',
  ],
  'Barva': [
    'Barva',
    'San Pedro',
    'San Pablo',
    'San Roque',
    'Santa Lucía',
    'San José de la Montaña',
  ],
  'Santo Domingo': [
    'Santo Domingo',
    'San Vicente',
    'San Miguel',
    'Paracito',
    'Santo Tomás',
    'Santa Rosa',
    'Tures',
    'Pará',
  ],
  'Santa Bárbara': [
    'Santa Bárbara',
    'San Pedro',
    'San Juan',
    'Jesús',
    'Santo Domingo',
    'Purabá',
  ],
  'San Rafael': [
    'San Rafael',
    'San Josecito',
    'Santiago',
    'Ángeles',
    'Concepción',
  ],
  'San Isidro': [
    'San Isidro',
    'San José',
    'Concepción',
    'San Francisco',
  ],
  'Belén': [
    'San Antonio',
    'La Ribera',
    'La Asunción',
  ],
  'Flores': [
    'San Joaquín',
    'Barrantes',
    'Llorente',
  ],
  'San Pablo': [
    'San Pablo',
    'Rincón de Sabanilla',
  ],
  'Sarapiquí': [
    'Puerto Viejo',
    'La Virgen',
    'Las Horquetas',
    'Llanuras del Gaspar',
    'Cureña',
  ],
  'Liberia': [
    'Liberia',
    'Cañas Dulces',
    'Mayorga',
    'Nacascolo',
    'Curubandé',
  ],
  'Nicoya': [
    'Nicoya',
    'Mansión',
    'San Antonio',
    'Quebrada Honda',
    'Sámara',
    'Nosara',
    'Belén de Nosarita',
  ],
  'Santa Cruz': [
    'Santa Cruz',
    'Bolsón',
    'Veintisiete de Abril',
    'Tempate',
    'Cartagena',
    'Cuajiniquil',
    'Diriá',
    'Cabo Velas',
    'Tamarindo',
  ],
  'Bagaces': [
    'Bagaces',
    'La Fortuna',
    'Mogote',
    'Río Naranjo',
    'Pijije',
  ],
  'Carrillo': [
    'Filadelfia',
    'Palmira',
    'Sardinal',
    'Belén',
  ],
  'Cañas': [
    'Cañas',
    'Palmira',
    'San Miguel',
    'Bebedero',
    'Porozal',
  ],
  'Abangares': [
    'Las Juntas',
    'Sierra',
    'San Juan',
    'Colorado',
  ],
  'Tilarán': [
    'Tilarán',
    'Quebrada Grande',
    'Tronadora',
    'Santa Rosa',
    'Líbano',
    'Tierras Morenas',
    'Arenal',
    'Cabeceras',
  ],
  'Nandayure': [
    'Carmona',
    'Santa Rita',
    'Zapotal',
    'San Pablo',
    'Porvenir',
    'Bejuco',
  ],
  'La Cruz': [
    'La Cruz',
    'Santa Cecilia',
    'La Garita',
    'Santa Elena',
  ],
  'Hojancha': [
    'Hojancha',
    'Monte Romo',
    'Puerto Carrillo',
    'Huacas',
    'Matambú',
  ],
  'Puntarenas': [
    'Puntarenas',
    'Pitahaya',
    'Chomes',
    'Lepanto',
    'Paquera',
    'Manzanillo',
    'Guacimal',
    'Barranca',
    'Monte Verde',
    'Isla del Coco',
    'Cóbano',
    'Chacarita',
    'Chira',
    'Acapulco',
    'El Roble',
    'Arancibia',
  ],
  'Esparza': [
    'Espíritu Santo',
    'San Juan Grande',
    'Macacona',
    'San Rafael',
    'San Jerónimo',
    'Caldera',
  ],
  'Buenos Aires': [
    'Buenos Aires',
    'Volcán',
    'Potrero Grande',
    'Boruca',
    'Pilas',
    'Colinas',
    'Chánguena',
    'Biolley',
    'Brunka',
    'Cabagra',
  ],
  'Montes de Oro': [
    'Miramar',
    'La Unión',
    'San Isidro',
  ],
  'Osa': [
    'Puerto Cortés',
    'Palmar',
    'Sierpe',
    'Bahía Ballena',
    'Piedras Blancas',
    'Bahía Drake',
  ],
  'Quepos': [
    'Quepos',
    'Savegre',
    'Naranjito',
  ],
  'Golfito': [
    'Golfito',
    'Puerto Jiménez',
    'Guaycará',
    'Pavón',
  ],
  'Coto Brus': [
    'San Vito',
    'Sabalito',
    'Aguabuena',
    'Limoncito',
    'Pittier',
    'Gutiérrez Braun',
  ],
  'Parrita': [
    'Parrita',
  ],
  'Corredores': [
    'Corredor',
    'La Cuesta',
    'Canoas',
    'Laurel',
  ],
  'Garabito': [
    'Jacó',
    'Tárcoles',
    'Lagunillas',
  ],
  'Monteverde': [
    'Santa Elena',
  ],
  'Puerto Jiménez': [
    'Puerto Jiménez',
  ],
  'Limón': [
    'Limón',
    'Valle La Estrella',
    'Río Blanco',
    'Matama',
  ],
  'Pococí': [
    'Guápiles',
    'Jiménez',
    'Rita',
    'Roxana',
    'Cariari',
    'Colorado',
    'La Colonia',
  ],
  'Siquirres': [
    'Siquirres',
    'Pacuarito',
    'Florida',
    'Germania',
    'El Cairo',
    'Alegría',
    'Reventazón',
  ],
  'Talamanca': [
    'Bratsi',
    'Sixaola',
    'Cahuita',
    'Telire',
  ],
  'Matina': [
    'Matina',
    'Batán',
    'Carrandi',
  ],
  'Guácimo': [
    'Guácimo',
    'Mercedes',
    'Pocora',
    'Río Jiménez',
    'Duacarí',
  ],
};

export function obtenerCantonesDeProvincia(provincia: string): string[] {
  return CANTONES_POR_PROVINCIA[provincia] ?? [];
}

export function obtenerDistritosDeCanton(canton: string): string[] {
  return DISTRITOS_POR_CANTON[canton] ?? [];
}
